apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: prometheus-ds
spec:
  datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: https://thanos-querier.openshift-monitoring.svc.cluster.local:9091
      jsonData:
        tlsSkipVerify: true
      secureJsonData:
        httpHeaderValue1: "${PROM_TOKEN}"
  envFrom:
    - secretRef:
        name: grafana-prometheus-token
