apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-prometheus-datasource
  namespace: monitoring-tools
data:
  prometheus-datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: https://thanos-querier.openshift-monitoring.svc.cluster.local:9091
        isDefault: true
        jsonData:
          tlsSkipVerify: true
        secureJsonData:
          httpHeaderValue1: ${PROM_TOKEN}
