apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring-tools

resources:
  - grafana.yaml
  - grafana-ds-prometheus.yaml
  - grafana-ds-mlflow.yaml        # ðŸ‘ˆ AGGIUNGI QUESTA
  - grafana-dashboard-providers.yaml  # ðŸ‘ˆ AGGIUNGI QUESTA
  - secret-prometheus-token.yaml
  - sa-token-refresher.yaml
  - rbac-token-refresher.yaml
  - cronjob-token-refresher.yaml

configMapGenerator:
  - name: grafana-dashboard-mlflow
    files:
      - dashboards/mlflow-training-dashboard.json

  - name: grafana-dashboard-vllm
    files:
      - dashboards/vllm-dashboard.json

generatorOptions:
  disableNameSuffixHash: true
